# Generated by Django 5.2.7 on 2025-10-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=100)),
                ('cron_expression', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed'), ('Retrying', 'Retrying')], default='Pending', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('next_run_time', models.DateTimeField(blank=True, null=True)),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='scheduler.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed'), ('Retrying', 'Retrying')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.task')),
            ],
        ),
    ]
